%S07_MAKEFIGURES  Regenerate every figure in results/figures from the raw results.
%
%   No hand-made plots anywhere in the paper. If a figure cannot be
%   regenerated by this script, it does not go in.
%
%   Milestone: M7.  Blueprint: section 7.
%
%   STATUS: stub. Run order is s01 -> s08; each script is idempotent.
%
%   Usage:
%       setupPaths;
%       s07_makeFigures

setupPaths;
rng(defaultConfig().seed, 'twister');

error('HimigTransform:NotImplemented', ...
    's07_makeFigures is a stub (Milestone M7). See docs/designNotes.md.');
